#!/usr/bin/env node
// status.mjs — read-only emitter of a current-state markdown block.
//
// Scans src/content/*, scripts/, dist/, and the Dropbox vault and prints
// a markdown block suitable for pasting into the STATUS region of CLAUDE.md
// (between <!-- STATUS:BEGIN --> and <!-- STATUS:END -->).
//
// Usage:  node scripts/status.mjs
// Never writes files. Safe to run any time.

import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const CONTENT = path.join(ROOT, "src", "content");
const SCRIPTS = path.join(ROOT, "scripts");
const DIST = path.join(ROOT, "dist");
const VAULT_DEFAULT = path.join(
  process.env.HOME ?? "",
  "Library/CloudStorage/Dropbox/CRFW/CRFW Archive/_Vault"
);
const VAULT = process.env.CRFW_VAULT ?? VAULT_DEFAULT;

function listFiles(dir, exts) {
  if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => exts.some((e) => f.endsWith(e)))
    .map((f) => path.join(dir, f));
}

function readJson(file) {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8"));
  } catch {
    return null;
  }
}

// Per src/content/config.ts: collections share a `published` boolean that
// defaults to true everywhere except photos (where it defaults to false
// — photos are draft until explicitly approved).
const PUBLISHED_DEFAULT_FALSE = new Set(["photos"]);

function isPublished(entry, collection) {
  if (!entry || typeof entry !== "object") return false;
  if (entry.published === true) return true;
  if (entry.published === false) return false;
  return !PUBLISHED_DEFAULT_FALSE.has(collection);
}

function readMdFrontmatter(file) {
  const src = fs.readFileSync(file, "utf8");
  if (!src.startsWith("---")) return {};
  const end = src.indexOf("\n---", 3);
  if (end < 0) return {};
  const fm = src.slice(3, end);
  const obj = {};
  for (const line of fm.split("\n")) {
    const m = /^(\w+):\s*(.*)$/.exec(line);
    if (!m) continue;
    const [, k, raw] = m;
    const v = raw.trim();
    if (v === "true") obj[k] = true;
    else if (v === "false") obj[k] = false;
    else obj[k] = v.replace(/^["']|["']$/g, "");
  }
  return obj;
}

function collectionStats(name) {
  const dir = path.join(CONTENT, name);
  const files = listFiles(dir, [".json", ".md"]);
  let published = 0;
  for (const f of files) {
    const entry = f.endsWith(".json") ? readJson(f) : readMdFrontmatter(f);
    if (isPublished(entry, name)) published++;
  }
  return { total: files.length, published };
}

function vaultStats(kind) {
  const dir = path.join(VAULT, kind);
  const aux = new Set(["README.md", "INDEX.md", "SCHEMA.md", "NOTES.md"]);
  return listFiles(dir, [".md"]).filter((p) => !aux.has(path.basename(p))).length;
}

function countHtmlPages(dir) {
  if (!fs.existsSync(dir)) return null;
  let n = 0;
  const walk = (d) => {
    for (const ent of fs.readdirSync(d, { withFileTypes: true })) {
      if (ent.isDirectory()) walk(path.join(d, ent.name));
      else if (ent.name.endsWith(".html")) n++;
    }
  };
  walk(dir);
  return n;
}

const siteCollections = [
  "releases",
  "photos",
  "videos",
  "voice_memos",
  "events",
  "sets",
];
const vaultCollections = [
  "people",
  "projects",
  "press",
  "venues",
  "organizations",
  "funds",
  "grants",
  "releases",
  "tracks",
  "events",
  "series",
  "motifs",
];

const siteRows = siteCollections.map((c) => [c, collectionStats(c)]);
const vaultRows = vaultCollections.map((c) => {
  const projDir = `vault_${c}`;
  const projected = collectionStats(projDir);
  const source = fs.existsSync(VAULT) ? vaultStats(c) : null;
  return { kind: c, projected: projected.total, source };
});

const scripts = listFiles(SCRIPTS, [".mjs"])
  .map((p) => path.basename(p))
  .sort();

const pageCount = countHtmlPages(DIST);
const vaultOk = fs.existsSync(VAULT);

const lines = [];
lines.push(`_generated by \`node scripts/status.mjs\` on ${new Date().toISOString().slice(0, 10)}._`);
lines.push("");
lines.push("### Site content collections");
lines.push("| collection | total | published |");
lines.push("|---|---:|---:|");
for (const [name, s] of siteRows) {
  lines.push(`| ${name} | ${s.total} | ${s.published} |`);
}
lines.push("");
lines.push("### Vault (projection ↔ source)");
if (!vaultOk) {
  lines.push(`_Vault source not found at \`${VAULT}\` — source counts skipped._`);
  lines.push("");
}
lines.push("| kind | projected (src/content/vault_*) | source (_Vault/) |");
lines.push("|---|---:|---:|");
for (const r of vaultRows) {
  lines.push(`| ${r.kind} | ${r.projected} | ${r.source ?? "—"} |`);
}
lines.push("");
lines.push("### Scripts");
lines.push(`${scripts.length} scripts in \`scripts/\`:`);
lines.push("");
lines.push(scripts.map((s) => `- \`${s}\``).join("\n"));
lines.push("");
lines.push("### Build output");
if (pageCount == null) {
  lines.push("_No `dist/` — run `npm run build` to populate._");
} else {
  lines.push(`\`dist/\` has **${pageCount}** HTML pages.`);
}

process.stdout.write(lines.join("\n") + "\n");
